name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Configure npm retries
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-timeout 600000
          npm config set prefer-offline true
      - name: Jitter to avoid registry burst
        run: |
          JITTER=$((RANDOM % 20 + 5))
          echo "Sleeping $JITTER seconds to reduce chance of 429..." && sleep $JITTER
      - name: Install deps (with retry)
        run: |
          n=0
          until [ $n -ge 3 ]; do
            npm ci --no-audit --no-fund && break
            n=$((n+1))
            echo "npm ci failed (attempt $n), retrying in $((2**n))s..."
            sleep $((2**n))
          done
          if [ $n -ge 3 ]; then
            echo "npm ci failed after retries; attempting fallback npm install" >&2
            npm install --no-audit --no-fund || { echo "Fallback npm install failed" >&2; exit 1; }
          fi
          # Workaround Rollup native binary missing on linux
          npm install --no-save @rollup/rollup-linux-x64-gnu || true
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --ci --silent
      - name: Build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  pages-deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Configure npm retries
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-timeout 600000
          npm config set prefer-offline true
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
